Exception ignored in: <_io.FileIO name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON1207_18.log' mode='ab' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/antoine/dev/python/packages/pyaf/logs/M4_COMP_ECONOMICS/PyAF_M4_COMP_ECONOMICS_ECON1207_18.log' mode='a' encoding='UTF-8'>
BENCH_DATA M4_COMP_ECONOMICS
TIME :  Date N= 16 H= 6 HEAD= [0 1 2 3 4] TAIL= [11 12 13 14 15]
SIGNAL :  ECON1229 N= 16 H= 6 HEAD= [ 22697.482    22697.26756  22687.25994  22695.92226  22693.86545] TAIL= [ 22686.84     20860.03363  20848.64603  20827.9      21727.84   ]
      ECON1229  Date
0  22697.48200     0
1  22697.26756     1
2  22687.25994     2
3  22695.92226     3
4  22693.86545     4
<class 'pandas.core.frame.DataFrame'>
Int64Index: 16 entries, 0 to 15
Data columns (total 2 columns):
ECON1229    16 non-null float64
Date        16 non-null int64
dtypes: float64(1), int64(1)
memory usage: 384.0 bytes
None
SCIKIT_MODEL_FEATURE_SELECTION_FAILURE RelDiff_ECON1229_ConstantTrend_residue_zeroCycle_residue_AR(4) (16, 4) divide by zero encountered in true_divide
BENCHMARK_FAILURE 'M4_COMP_ECONOMICS_ECON1229_6'
